In [ ]:
# Mmembuat segitiga dengan bintang
tinggi = int(input("Masukkan tinggi segitiga: "))

print("")

for i in range(tinggi,0,-1):
   print("*" * i)

Masukkan tinggi segitiga: 5

*****
****
***
**
*


In [20]:
# Membuat segitiga dengan angka
tinggi = int(input("Masukkan tinggi segitiga: "))

angka = 1

for i in range(1, tinggi + 1):
    for j in range(i):
        print(angka, end=' ')
        angka += 1
    print()


Masukkan tinggi segitiga: 4
1 
2 3 
4 5 6 
7 8 9 10 


In [1]:
# algoritma searching
a = [1, 6, 8, 9, 10]
target = 9

for i in range(len(a)):
    if a[i] == target:
        print(f"Nilai {target} ditemukan pada indeks {i}.")
        break

else:
    print(f"Nilai {target} tidak ditemukan dalam array.")


Nilai 9 ditemukan pada indeks 3.


In [2]:
#algoritma sorting
import numpy as np
a=np.array([7,6,8,1,3])
c=0

panjang=len(a)
print("sebelum dilakuakan pengurutan")
print(a)
print("proses pengurutan")
for i in range(panjang-1):
  for j in range(panjang-1):
    if(a[j]>a[j+1]):
      c=a[j+1]
      a[j+1]=a[j]
      a[j]=c
      print(a)

print("-------------------------------------------------")
print("setelah dilakukan pengurutan", a)


sebelum dilakuakan pengurutan
[7 6 8 1 3]
proses pengurutan
[6 7 8 1 3]
[6 7 1 8 3]
[6 7 1 3 8]
[6 1 7 3 8]
[6 1 3 7 8]
[1 6 3 7 8]
[1 3 6 7 8]
-------------------------------------------------
setelah dilakukan pengurutan [1 3 6 7 8]


In [ ]:
#cara membuat list
from collections import deque
a = deque(["pakaian", 10 , 1000])
print("list awal = ", a)

a.append("celana")
a.append(90)
a.append(1500)
print("setelah ditambah, list = ", a)

a.popleft()
print("setelah di pop, list = ", a)

list awal =  deque(['pakaian', 10, 1000])
setelah ditambah, list =  deque(['pakaian', 10, 1000, 'celana', 90, 1500])
setelah di pop, list =  deque([10, 1000, 'celana', 90, 1500])


In [ ]:
#algoritma stack
a = (["pisang",5,5000,"apel",10,1000,"alpukat",5,1000])
print("daftar : ",a)

a.append(10)
print(a)

a.append("buah naga")
print(a)

a.pop()
print(a)

daftar :  ['pisang', 5, 5000, 'apel', 10, 1000, 'alpukat', 5, 1000]
['pisang', 5, 5000, 'apel', 10, 1000, 'alpukat', 5, 1000, 10]
['pisang', 5, 5000, 'apel', 10, 1000, 'alpukat', 5, 1000, 10, 'buah naga']
['pisang', 5, 5000, 'apel', 10, 1000, 'alpukat', 5, 1000, 10]


In [ ]:
#algoritma stack quee/antrian
from collections import deque
a= deque(["pisang", 3000, "durian", 10000, "rambutan", 500])
print("daftar : ", a)

a.append("jagung")
print (a)

a.append("mangga")
print(a)

a.popleft()
print(a)


daftar :  deque(['pisang', 3000, 'durian', 10000, 'rambutan', 500])
deque(['pisang', 3000, 'durian', 10000, 'rambutan', 500, 'jagung'])
deque(['pisang', 3000, 'durian', 10000, 'rambutan', 500, 'jagung', 'mangga'])
deque([3000, 'durian', 10000, 'rambutan', 500, 'jagung', 'mangga'])


In [19]:
#algoritma stack dengan style OOP
class Pakaian :
  def __init__(self):
    self.items = []

  def add(self, item):
    self.items.append(item)

  def pop(self):
    if self.items:
      return self.items.pop()
      return None

  def show(self):
    print(self.items)

a = Pakaian()

print("==========================isi awal list=========================")
a.add("kemeja")
a.add("celana")
a.add("sepatu")
a.show()
print("========================setelah ditambah========================")



a.add("kaos")
a.add("sabuk")
a.add("sandal")
a.show()

a.pop()
print("======================setelah di hapus/pop======================")
a.show()



==========================isi awal list=========================
['kemeja', 'celana', 'sepatu']
========================setelah ditambah========================
['kemeja', 'celana', 'sepatu', 'kaos', 'sabuk', 'sandal']
======================setelah di hapus/pop======================
['kemeja', 'celana', 'sepatu', 'kaos', 'sabuk']


In [ ]:
#algoritma stack quee dengan style oop
from collections import deque

class Mahasiswa:
  def __init__(self):
    self.data = deque()

  def tambah(self, nama, jurusan):
    self.data.append((nama, jurusan))

  def show(self):
    if not self.data:
      print("data kosong.")
    else:
      print("data saat ini :")
    for nama, jurusan in self.data:
      print(f"nama: {nama}, Jurusan: {jurusan}")

  def hapus(self):
    if self.data:
      nama = self.data.popleft()
      print(f"mahasiswa: {nama} telah dihapus")
    else:
        print("data kosong.")

data = Mahasiswa()

data.tambah("Ian", "informatika")
data.tambah("dita", "informatika")
data.tambah("leni", "informatika")

print("==========data awal==========")
data.show()


data.tambah("Nika","informatika")
print("==========setelah ditambah==========")
data.show()

data.hapus()
print("==========setelah dihapus==========")
data.show()

==========data awal==========
data saat ini :
nama: Ian, Jurusan: informatika
nama: dita, Jurusan: informatika
nama: leni, Jurusan: informatika
==========setelah ditambah==========
data saat ini :
nama: Ian, Jurusan: informatika
nama: dita, Jurusan: informatika
nama: leni, Jurusan: informatika
nama: Nika, Jurusan: informatika
mahasiswa: ('Ian', 'informatika') telah dihapus
==========setelah dihapus==========
data saat ini :
nama: dita, Jurusan: informatika
nama: leni, Jurusan: informatika
nama: Nika, Jurusan: informatika


In [22]:
#membuat Binary Tree


# Fungsi untuk membuat node baru
def create_node(data):
    return {"data": data, "left": None, "right": None}

# Fungsi untuk menambahkan node ke Binary Tree
def insert(root, data):
    if root is None:
        return create_node(data)
    if data < root["data"]:
        root["left"] = insert(root["left"], data)
    else:
        root["right"] = insert(root["right"], data)
    return root

# Fungsi untuk Preorder Traversal (Root, Left, Right)
def preorder_traversal(root):
    if root is not None:
        print(root["data"], end=" ")
        preorder_traversal(root["left"])
        preorder_traversal(root["right"])

# Fungsi untuk Inorder Traversal (Left, Root, Right)
def inorder_traversal(root):
    if root is not None:
        inorder_traversal(root["left"])
        print(root["data"], end=" ")
        inorder_traversal(root["right"])

# Fungsi untuk Postorder Traversal (Left, Right, Root)
def postorder_traversal(root):
    if root is not None:
        postorder_traversal(root["left"])
        postorder_traversal(root["right"])
        print(root["data"], end=" ")

# Fungsi Levelorder Traversal (up to down from root)
from collections import deque
def levelorder_traversal(root):
    if root is None:
        return

    queue = deque([root])
    while queue:
        current = queue.popleft()
        print(current["data"], end=" ")

        if current["left"]:
            queue.append(current["left"])
        if current["right"]:
            queue.append(current["right"])



# Membuat tree dan menambahkan elemen
root = None
root = insert(root, 10)
root = insert(root, 5)
root = insert(root, 15)
root = insert(root, 2)
root = insert(root, 7)

# Traversal
print("Preorder Traversal:")
preorder_traversal(root)

print("\nInorder Traversal:")
inorder_traversal(root)

print("\nPostorder Traversal:")
postorder_traversal(root)

print("\nLevelorder Traversal:")
levelorder_traversal(root)


Preorder Traversal:
10 5 2 7 15 
Inorder Traversal:
2 5 7 10 15 
Postorder Traversal:
2 7 5 15 10 
Levelorder Traversal:
10 5 15 2 7 